routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//frontend flexshop
Route::get('/demo','FlexshopController@index')->name('homePage');
Route::group(['prefix'=>'demo'],function (){
    //project
    Route::get('/danh-sach-du-an','FlexshopController@getListProject')->name('listProjects');
    Route::get('/danh-sach-du-an/{id}/{cateSlug}','FlexshopController@cateProject')->name('cateListProject');
    Route::get('/du-an/{id}/{projectSlug}','FlexshopController@singleProject')->name('postProject');
    //product
    Route::get('/danh-sach-san-pham','FlexshopController@getListProduct')->name('getListProduct');
    Route::get('/danh-sach-san-pham/{id}/{cateSlug}','FlexshopController@cateProduct')->name('cateListProduct');
    Route::get('/danh-sach-san-pham/{id}/{cateSlug}/list','FlexshopController@listProduct')->name('listProduct');
    Route::get('/san-pham/{id}/{productSlug}','FlexshopController@singleProduct')->name('postProduct');
});


//*******************
Route::get('/', 'HomeController@index')->name('trangchu');
Route::get('/news/{id}/{newsSlug}', 'HomeController@singlepost')->name('postNews');
Route::get('/cate/{id}/{cateSlug}', 'HomeController@catepost')->name('catePost');
Route::get('/tags/{id}/{tagSlug}', 'HomeController@tagpost')->name('tagPost');
Route::get('/cateprod/{id}/{cateProdSlug}', 'HomeController@getCateProd')->name('cateProd');
Route::get('/prod/{id}/{prodSlug}', 'HomeController@getDetailProd')->name('hotProd');
Route::get('listprods','HomeController@getListProds')->name('listProds');
//backend
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::group(['prefix' => 'panel'], function () {
        //category
        Route::resource('category', 'CateController', ['except' => 'destroy']);
        Route::get('category/{idDelete}/destroy', 'CateController@destroy')->name('category.delete');
        //category product
        Route::resource('cateprod', 'CateProdController', ['except' => 'destroy']);
        Route::get('cateprod/{idDelete}/destroy', 'CateProdController@destroy')->name('cateprod.delete');
        //Prods
        Route::resource('prods', 'ProdsController', ['except' => 'destroy']);
        Route::get('prods/{idDelete}/destroy', 'ProdsController@destroy')->name('prods.delete');
        //article
        Route::resource('news', 'NewsController', ['except' => 'destroy']);
        Route::get('news/{idDelete}/destroy', 'NewsController@destroy')->name('news.delete');
        //slider
        Route::resource('slider','SliderController',['except' => 'destroy']);
        Route::get('slider/{idDelete}/destroy','SliderController@destroy')->name('slider.delete');
        //partner
        Route::resource('partner','PartnerController',['except' => 'destroy']);
        Route::get('partner/{idDelete}/destroy','PartnerController@destroy')->name('partner.delete');
        //tags
        Route::resource('tags', 'TagsController', ['except' => 'destroy']);
        Route::get('tags/{idDelete}/destroy', 'TagsController@destroy')->name('tags.delete');
        //user
        Route::resource('user', 'UserController');
    });
});

Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $table= 'users';

    public function user_roles(){
        return $this->hasMany('App\User_role','user_id','id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Users\UsersRepositoryInterface;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $_user;
    public function __construct(UsersRepositoryInterface $repository)
    {
        $this->_user= $repository;
    }

    public function index()
    {
        $getData=$this->_user->getUserInfor();
        return view('admin.users.list')->with(['users'=>$getData]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $getData=$this->_user->getUserInfor();
        return view('admin.users.create')->with(['users'=>$getData]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $getData= $this->_user->getCreateAndEdit($request->all());
        return $getData;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $getData= $this->_user->getUserInfor($id);
        return view('admin.users.edit')->with(['getUsers'=>$getData['abc'],'getRoles'=>$getData['123'],'RolCheck'=>$getData['RolChecked']]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $getData= $this->_user->getCreateAndEdit($request->all(),$id);
        return $getData;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/users/create.blade.php
@extends('template')
@section('title')
    Create news - @parent
@endsection
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-md-12">
                        @include('admin.partial.errors')
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="p-20">
                            {!! Form::open(['route' => 'user.store','class'=>'form-horizontal','role'=>'form','enctype'=>'multipart/form-data']) !!}
                            <div class="form-group">
                                {!! Form::label('Username','Username',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    {!! Form::text('txtUser',old('txtUser'),['placeholder'=>'To type here','class'=>'form-control']) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('input select','Input Select',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    {!! Form::select('slRoles', ['1' => 'Administrator', '2' => 'Moderator','3'=>'Editor'], null, ['placeholder' => 'Chọn chức vụ...','class'=>'form-control']) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('E-mail','E-mail',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    {!! Form::text('txtEmail',old('txtEmail'),['placeholder'=>'To type here if any','class'=>'form-control']) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('Phone Number','Phone Number',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    {!! Form::text('txtPhone',old('txtPhone'),['placeholder'=>'To type here if any','class'=>'form-control']) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('Password','Password',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    {!! Form::text('txtPass',old('txtPass'),['placeholder'=>'To type here','class'=>'form-control']) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('Check Roles','Check Roles',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    <ul>
                                        @foreach($users['123'] as $us)
                                            <li>{!! Form::checkbox('roles[]',$us->id, null,['style'=>'visibility:visible']) !!} {{$us->portray}}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label(' ',' ',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    {!! Form::button('Click me, Please!',['class'=>'btn btn-custom waves-effect waves-light btn-md','type'=>'submit']) !!}
                                </div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>

                </div>
                <!-- end row -->

            </div> <!-- end card-box -->
        </div><!-- end col -->
    </div>
    <!-- end row -->
@endsection
@section('jsfiles')
    <!-- Jquery filer js -->
    <script src="{{asset('public/backend/plugins/jquery.filer/js/jquery.filer.min.js')}}"></script>
    <!-- Bootstrap fileupload js -->
    <script src="{{asset('public/backend/plugins/bootstrap-fileupload/bootstrap-fileupload.js')}}"></script>
    <!-- page specific js -->
    <script src="{{asset('public/backend/pages/jquery.fileuploads.init.js')}}"></script>
@endsection

resources/views/admin/users/edit.blade.php
@extends('template')
@section('title')
    Create news - @parent
@endsection
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-md-12">
                        @include('admin.partial.errors')
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="p-20">
                            {!! Form::open(['route' =>['user.update',$getUsers->id],'class'=>'form-horizontal','role'=>'form','method'=>'put','enctype'=>'multipart/form-data']) !!}
                            <div class="form-group">
                                {!! Form::label('Username','Username',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    {!! Form::text('txtUser',old('txtUser',isset($getUsers)?$getUsers->name:null),['placeholder'=>'To type here','class'=>'form-control']) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('input select','Input Select',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    {!! Form::select('slRoles', ['1' => 'Administrator', '2' => 'Moderator','3'=>'Editor'], $getUsers->lvl, ['placeholder' => 'Chọn chức vụ...','class'=>'form-control']) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('E-mail','E-mail',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    {!! Form::text('txtEmail',old('txtEmail',isset($getUsers)?$getUsers->email:null),['placeholder'=>'To type here if any','class'=>'form-control']) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('Phone Number','Phone Number',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    {!! Form::text('txtPhone',old('txtPhone',isset($getUsers)?$getUsers->phone:null),['placeholder'=>'To type here if any','class'=>'form-control']) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('Password','Password',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    {!! Form::text('txtPass',old('txtPass',isset($getUsers)?$getUsers->password:null),['placeholder'=>'To type here','class'=>'form-control']) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('Check Roles','Check Roles',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    <ul>
                                        @foreach($RolCheck as $getData)
                                                @php
                                                    $save='';
                                                    if (!empty($getData['chek'])){
                                                                    foreach ($getData['chek'] as $chk){
                                                                        if ($chk->role_id == $getData['id']){
                                                                            $save='checked';
                                                                        }
                                                                    }
                                                                }
                                                @endphp
                                            <li>{!! Form::checkbox('roles[]',$getData['id'],$save,['style'=>'visibility:visible']) !!} {{$getData['name']}}</li>
                                        @endforeach

                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label(' ',' ',['class'=>'col-md-2 control-label']) !!}
                                <div class="col-md-10">
                                    {!! Form::button('Click me, Please!',['class'=>'btn btn-custom waves-effect waves-light btn-md','type'=>'submit']) !!}
                                </div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>

                </div>
                <!-- end row -->

            </div> <!-- end card-box -->
        </div><!-- end col -->
    </div>
    <!-- end row -->
@endsection
@section('jsfiles')
    <!-- Jquery filer js -->
    <script src="{{asset('public/backend/plugins/jquery.filer/js/jquery.filer.min.js')}}"></script>
    <!-- Bootstrap fileupload js -->
    <script src="{{asset('public/backend/plugins/bootstrap-fileupload/bootstrap-fileupload.js')}}"></script>
    <!-- page specific js -->
    <script src="{{asset('public/backend/pages/jquery.fileuploads.init.js')}}"></script>
@endsection

resources/views/admin/users/list.blade.php
@extends('template')
@section('content')
    <div class="row">
        <div class="col-md-12">
            @include('admin.partial.errors')
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box table-responsive">
                <table id="datatable-fixed-header" class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Username</th>
                        <th>E-mail</th>
                        <th>Roles</th>
                        <th>Phone Number</th>
                        <th>Token</th>
                        <th>Option</th>
                    </tr>
                    </thead>
                    @foreach($users['abc'] as $us)
                        <tr>
                            <td>{{$us->name}}</td>
                            <td>{{$us->email}}</td>
                            <td>admin</td>
                            <td>{{$us->phone}}</td>
                            <td>{{$us->remember_token}}</td>
                            <td>
                                <a href="{{route('user.edit',$us->id)}}"><button type="button" class="btn btn-icon waves-effect waves-light btn-warning">  <i class="fa fa-wrench"></i> </button></a>
                                <a href=""><button type="button" class="btn btn-icon waves-effect waves-light btn-danger"> <i class="fa fa-remove"></i> </button></a>
                            </td>
                        </tr>
                    @endforeach
                        </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('jstable')

    <!--js table-->
    <script src="{{asset('public/backend/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/buttons.bootstrap.min.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/jszip.min.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/pdfmake.min.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/vfs_fonts.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/buttons.html5.min.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/buttons.print.min.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/dataTables.fixedHeader.min.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/dataTables.keyTable.min.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/responsive.bootstrap.min.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/dataTables.scroller.min.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/dataTables.colVis.js')}}"></script>
    <script src="{{asset('public/backend/plugins/datatables/dataTables.fixedColumns.min.js')}}"></script>

    <!-- init -->
    <script src="{{asset('public/backend/pages/jquery.datatables.init.js')}}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
            $('#datatable-keytable').DataTable({keys: true});
            $('#datatable-responsive').DataTable();
            $('#datatable-colvid').DataTable({
                "dom": 'C<"clear">lfrtip',
                "colVis": {
                    "buttonText": "Change columns"
                }
            });
            $('#datatable-scroller').DataTable({
                ajax: "{{asset('public/backend/plugins/datatables/json/scroller-demo.json')}}",
                deferRender: true,
                scrollY: 380,
                scrollCollapse: true,
                scroller: true
            });
            var table = $('#datatable-fixed-header').DataTable({fixedHeader: true});
            var table = $('#datatable-fixed-col').DataTable({
                scrollY: "300px",
                scrollX: true,
                scrollCollapse: true,
                paging: false,
                fixedColumns: {
                    leftColumns: 1,
                    rightColumns: 1
                }
            });
        });
        TableManageButtons.init();

    </script>
@endsection