routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//frontend flexshop
Route::get('/demo','FlexshopController@index')->name('homePage');
Route::group(['prefix'=>'demo'],function (){
    //project
    Route::get('/danh-sach-du-an','FlexshopController@getListProject')->name('listProjects');
    Route::get('/danh-sach-du-an/{id}/{cateSlug}','FlexshopController@cateProject')->name('cateListProject');
    Route::get('/du-an/{id}/{projectSlug}','FlexshopController@singleProject')->name('postProject');
    //product
    Route::get('/danh-sach-san-pham','FlexshopController@getListProduct')->name('getListProduct');
    Route::get('/danh-sach-san-pham/{id}/{cateSlug}','FlexshopController@cateProduct')->name('cateListProduct');
    Route::get('/danh-sach-san-pham/{id}/{cateSlug}/list','FlexshopController@listProduct')->name('listProduct');
    Route::get('/san-pham/{id}/{productSlug}','FlexshopController@singleProduct')->name('postProduct');
});


//*******************
Route::get('/', 'HomeController@index')->name('trangchu');
Route::get('/news/{id}/{newsSlug}', 'HomeController@singlepost')->name('postNews');
Route::get('/cate/{id}/{cateSlug}', 'HomeController@catepost')->name('catePost');
Route::get('/tags/{id}/{tagSlug}', 'HomeController@tagpost')->name('tagPost');
Route::get('/cateprod/{id}/{cateProdSlug}', 'HomeController@getCateProd')->name('cateProd');
Route::get('/prod/{id}/{prodSlug}', 'HomeController@getDetailProd')->name('hotProd');
Route::get('listprods','HomeController@getListProds')->name('listProds');
//backend
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::group(['prefix' => 'panel'], function () {
        //category
        Route::resource('category', 'CateController', ['except' => 'destroy']);
        Route::get('category/{idDelete}/destroy', 'CateController@destroy')->name('category.delete');
        //category product
        Route::resource('cateprod', 'CateProdController', ['except' => 'destroy']);
        Route::get('cateprod/{idDelete}/destroy', 'CateProdController@destroy')->name('cateprod.delete');
        //Prods
        Route::resource('prods', 'ProdsController', ['except' => 'destroy']);
        Route::get('prods/{idDelete}/destroy', 'ProdsController@destroy')->name('prods.delete');
        //article
        Route::resource('news', 'NewsController', ['except' => 'destroy']);
        Route::get('news/{idDelete}/destroy', 'NewsController@destroy')->name('news.delete');
        //slider
        Route::resource('slider','SliderController',['except' => 'destroy']);
        Route::get('slider/{idDelete}/destroy','SliderController@destroy')->name('slider.delete');
        //partner
        Route::resource('partner','PartnerController',['except' => 'destroy']);
        Route::get('partner/{idDelete}/destroy','PartnerController@destroy')->name('partner.delete');
        //tags
        Route::resource('tags', 'TagsController', ['except' => 'destroy']);
        Route::get('tags/{idDelete}/destroy', 'TagsController@destroy')->name('tags.delete');
        //user
        Route::resource('user', 'UserController');
    });
});

Auth::routes();

resources/views/admin/partial/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger alert-dismissible fade in fadeout" role="alert">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session('thongbao'))
    <div class="alert alert-success alert-dismissible fade in fadeout" role="alert">
        <strong>{{session('thongbao')}}</strong> successfully!
    </div>
@endif
@if(session('thongbaoloi'))
    <div class="alert alert-danger alert-dismissible fade in fadeout" role="alert">
        <strong>{{session('thongbaoloi')}}</strong>, phải xóa hết mục con
    </div>
@endif

resources/views/admin/partial/navleft.blade.php
<div class="left side-menu">
    <div class="slimscroll-menu" id="remove-scroll">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metisMenu nav" id="side-menu">
                <li class="menu-title">Navigation</li>
                <li>
                    <a href="javascript: void(0);" aria-expanded="true"><i class="fi-air-play"></i><span class="badge badge-success pull-right">2</span> <span> Dashboard </span></a>
                    <ul class="nav-second-level nav" aria-expanded="true">
                        <li><a href="index.html">Dashboard 1</a></li>
                        <li><a href="dashboard-2.html">Dashboard 2</a></li>
                    </ul>
                </li>
				<li>
                    <a href="javascript: void(0);" aria-expanded="true"><i class="fi-menu"></i> <span> Categories </span> <span class="menu-arrow"></span></a>
                    <ul class="nav-second-level nav" aria-expanded="true">
                        <li><a href="{{route('category.create')}}"><i class="fi-circle-plus"></i> Add Category</a></li>
                        <li><a href="{{route('category.index')}}"><i class="fi-layers"></i> List Categories</a></li>
                    </ul>
                </li>
                <li>
                    <a href="javascript: void(0);" aria-expanded="true"><i class="fi-paper"></i> <span> Article </span> <span class="menu-arrow"></span></a>
                    <ul class="nav-second-level nav" aria-expanded="true">
                        <li><a href="{{route('news.create')}}"><i class="fi-circle-plus"></i> Add Article</a></li>
                        <li><a href="{{route('news.index')}}"><i class="fi-layers"></i> List Articles</a></li>
                    </ul>
                </li>
                {{--<li>--}}
                    {{--<a href="javascript: void(0);" aria-expanded="true"><i class="fi-tag"></i> <span> Tags News</span> <span class="menu-arrow"></span></a>--}}
                    {{--<ul class="nav-second-level nav" aria-expanded="true">--}}
                        {{--<li><a href="{{route('tags.create')}}">Create Tag</a></li>--}}
                        {{--<li><a href="{{route('tags.index')}}">List Tags</a></li>--}}
                    {{--</ul>--}}
                {{--</li>--}}
                <li>
                    <a href="javascript: void(0);" aria-expanded="true"><i class="fi-air-play"></i> <span> Products </span> <span class="menu-arrow"></span></a>
                    <ul class="nav-second-level nav" aria-expanded="true">
                        <li><a href="{{route('cateprod.create')}}"><i class="fi-circle-plus"></i> Add Category</a></li>
                        <li><a href="{{route('cateprod.index')}}"><i class="fi-layers"></i> List Categories</a></li>
                        <li><a href="{{route('prods.create')}}"><i class="fi-circle-plus"></i> Add Product</a></li>
                        <li><a href="{{route('prods.index')}}"><i class="fi-layers"></i> List Products</a></li>
                    </ul>
                </li>
                <li>
                    <a href="javascript: void(0);" aria-expanded="true"><i class="fi-stack"></i> <span> Slider </span> <span class="menu-arrow"></span></a>
                    <ul class="nav-second-level nav" aria-expanded="true">
                        <li><a href="{{route('slider.create')}}"><i class="fi-circle-plus"></i> Add Slider</a></li>
                        <li><a href="{{route('slider.index')}}"><i class="fi-layers"></i> List Slider</a></li>
                    </ul>
                </li>
                <li>
                    <a href="javascript: void(0);" aria-expanded="true"><i class="fi-head"></i> <span> Partner </span> <span class="menu-arrow"></span></a>
                    <ul class="nav-second-level nav" aria-expanded="true">
                        <li><a href="{{route('partner.create')}}"><i class="fi-circle-plus"></i> Add Partner</a></li>
                        <li><a href="{{route('partner.index')}}"><i class="fi-layers"></i> List Partner</a></li>
                    </ul>
                </li>

{{--                <li>
                    <a href="javascript: void(0);" aria-expanded="true"><i class="fi-head"></i> <span> Users </span> <span class="menu-arrow"></span></a>
                    <ul class="nav-second-level nav" aria-expanded="true">
                        <li><a href="{{route('user.create')}}">Create News</a></li>
                        <li><a href="{{route('user.index')}}">List News</a></li>
                    </ul>
                </li>--}}
                <li><a href="calendar.html"><i class="fi-cog"></i> <span>Setting</span> </a></li>
            </ul>

        </div>
        <!-- Sidebar -->
        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>